##########################
##### Other Labels #######
##########################
 - name: "Blocked :no_entry_sign:"
   color: "F9D0C4"
 - name: "Blocking :exclamation:"
   description: "This issue is blocking work"
   color: "b60205"
 - name: "Cannot Reproduce"
   description: "This issue isn't reproducible"
   color: "D93F0B"
 - name: "Duplicate :grey_exclamation:"
   color: "fef2c0"
 - name: "Help Wanted :hand:"
   color: "0e8a16"
 - name: "Mesh Model Update Needed"
   color: "A5F5A0"
 - name: "Waiting On Future :calendar:"
   color: "C5DEF5"
 - name: "Waiting On Product"
   color: "C5DEF5"
 - name: "Urgent :bangbang:"
   color: "ce4727"
 - name: "On Hold"
   description: "Its on hold"
   color: "645460"
 - name: "Support Issue"
   description: "This issue comes from support"
   color: "fbca04"
 - name: "Triage"
   color: "0e8a16"
 - name: "VersionOne"
   description: "This comes from version one"
   color: "ea02b6"
 - name: "Test Ready"
   description: "This issue is ready for testing"
   color: "ea02b6"
 - name: "Deployment"
   description: "This issue is related to deployment"
   color: "8B354D"
 - name: "CR"
   description: "Change Request"
   color: "ffe600"
 - name: "Req. Design"
   description: "Requires design"
   color: "FBCA04"
   
#########################
##### Resolutions #######
#########################
 - name: "Resolution - Fixed"
   description: "This issue has been fixed"
   color: "A9E98F"
 - name: " Resolution - Rejected - Input Data Problem"
   description: "This issue has been rejected due to it being a issue with wrong input"
   color: "A9E98F"
 - name: "Resolution - Rejected"
   description: "This issue has been rejected"
   color: "A9E98F"
#########################
######## Costs  #########
#########################
 - name: "Cost - L"
   description: "Approximately 3 - 5 Months of work."
   color: "645460"
 - name: "Cost - M"
   description: "Approximately 1 - 2 Months of work."
   color: "645460"
 - name: "Cost - S"
   description: "Approximately 11 - 30 days of work."
   color: "645460"
 - name: "Cost - XL"
   description: "Approximately 6 - 12 Months of work."
   color: "645460"
 - name: "Cost - XXS"
   description: "Approximately 0 - 5 days of work."
   color: "645460"
 - name: "Cost - XS"
   description: "Approximately 6 - 10 days of work."
   color: "645460"
 - name: "Cost - XXL"
   description: "Approximately 12+ months of work."
   color: "645460"
#########################
######## Customer #######
#########################
 - name: "Customer - A2A"
   color: "c889d7"
 - name: "Customer - EPC"
   color: "c889d7"
 - name: "Customer - Enel"
   color: "c889d7"
 - name: "Customer - Iberdrola"
   color: "c889d7"
 - name: "Customer - Luminus"
   color: "c889d7"
 - name: "Customer - Uniper"
   color: "c889d7"
#########################
######## Priority #######
#########################
 - name: "Priority - High"
   color: "fef2c0"
 - name: "Priority - Low"
   color: "fef2c0"
 - name: "Priority - Medium"
   color: "fef2c0"
########################
######## Products ######
########################
 - name: "Product - Connecting Prodrisk"
   color: "5319e7"
 - name: "Product - Connecting Shop"
   color: "5319e7"
 - name: "Product - Spotbid"
   color: "5319e7"
 - name: "Product - Gateway"
   description: "Powel Optimal Gateway"
   color: "5319e7"
 - name: "Product - POH"
   color: "5319e7"
 - name: "Product - POM"
   description: "Powel Optimal Midterm"
   color: "5319e7"
 - name: "Product - POMA"
   color: "5319e7"
 - name: "Product - Optimal Log"
   color: "5319e7"
 - name: "Product - Battery"
   color: "5319e7"
#################
#### RISKS ######
#################
 - name: "Risk - High"
   description: "This change will likely break previous functionality"
   color: "b60205"
 - name: "Risk - Low"
   description: "This change will probably not break previous functionality"
   color: "006b75"
 - name: "Risk - Medium"
   description: "This change could break previous functionality"
   color: "1d76db"
 - name: "Risk - None"
   description: "This change will not break previous functionality"
   color: "006b75"
 - name: "Risk - TBD :question:"
   color: "006b75"
####################
#### Severity ######
####################
 - name: "Severity - Critical :boom:"
   description: "The software does not execute correctly. Severe adverse impact and no workaround."
   color: "c6bdf4"
 - name: "Severity - Major :fire:"
   description: "Major impairments in functionality. Major adverse impact and no workaround."
   color: "abcc53"
 - name: "Severity - Minor :construction:"
   description: "Minor impairments in functionality."
   color: "010fdf"
###############
### Types ##### (Automatic for PRs but not for issues)
###############
 - name: "Type - Bug :lady_beetle:"
   color: "b60205"
 - name: "Type - Bugfix" 
   color: "9E0717"
 - name: "Type - Cleanup :broom:"
   description: "Somebody needs to clean"
   color: "bfdadc"
 - name: "Type - Documentation :black_nib:"
   description: "Time to document!"
   color: "0052cc"
 - name: "Type - Enhancement :sparkler:"
   description: "Make something better"
   color: "9032f7"
 - name: "Type - Feature"
   color: "8feb7b"
 - name: "Type - Test"
   description: "Some test that has to be written"
   color: "ecb39f"
 - name: "Type - Other"
   description: "A miscellaneous issue"
   color: "ecb39f"
 - name: "Type - RFC"
   description: "Request For Comment"
   color: "ecb39f"
##################
### Versions #####
##################
 - name: "Develop"
   description: "Current development"
   color: "5978d8"
 - name: "v1.5.0"
   description: "Version 1.5.0"
   color: "5978d8"
 - name: "v1.6.0"
   description: "Version 1.6.0"
   color: "5978d8"
 - name: "v1.7.0"
   description: "Version 1.7.0"
   color: "5978d8"
 - name: "v1.7.1"
   description: "Version 1.7.1"
   color: "5978d8"
 - name: "v1.8.0"
   description: "Version 1.8.0"
   color: "5978d8"
 - name: "v1.9.0"
   description: "Version 1.9.0"
   color: "5978d8"
 - name: "v1.10.0"
   description: "Version 1.10.0"
   color: "5978d8"
 - name: "v1.11.0"
   description: "Version 1.11.0"
   color: "5978d8"
################################
### Fully Automated Labels #####
################################
 - name: "[X] Documented :scroll:"
   description: "Has been documented!"
   color: "0052cc"
 - name: "[X] Investigation :mag:"
   color: "D107F7"
 - name: "[X] Size - L"
   description: "PR: Changes between 100 - 500 lines"
   color: "0eb7c7"
 - name: "[X] Size - M"
   description: "PR: Changes between 40 - 100 lines"
   color: "0eb7c7"
 - name: "[X] Size - S"
   description: "PR: Changes between 10 - 30 lines"
   color: "0eb7c7"
 - name: "[X] Size - XL"
   description: "PR: Changes between 500 - 1000 lines"
   color: "0eb7c7"
 - name: "[X] Size - XS"
   description: "PR: Changes between 0 - 10 lines"
   color: "0eb7c7"
 - name: "[X] Size - XXL"
   description: "PR: Changes between 1000+ lines"
   color: "0eb7c7"
 - name: "[X] Accepted :heavy_check_mark:"
   color: "072dbc"
 - name: "[X] Awaiting Review :eyes:"
   color: "FBCA04"
 - name: "[X] Changes Requested :diamonds:"
   color: "f4ff1f"
 - name: "[X] In Progress :gear:"
   color: "C5DEF5"
 - name: "[X] Stale"
   color: "645460"
 - name: "[X] Needs documentation :pencil2:"
   description: "This needs to be documented!"
   color: "0052cc"
   
### STATE ####
 - name: "[X] :mailbox:"
   description: "New response to author"
   color: "0E8A16"
 - name: "[X] :basketball:"
   description: "The ball is in DevOps court"
   color: "D93F0B"
 - name: "[X] Waiting On Author"
   color: 0052CC
