name: Request for Comment [RFC] [Form]
description: This is a request for comment
title: "[RFC]: "
labels: ["Type - RFC", "Triage"]
body:
  - type: markdown
    attributes:
      value: |
        A Request for Comment
  - type: dropdown
    id: Product
    attributes:
      label: Product
      description: For which product is this Enchancemnet for?
      options:
        - POMA
        - POM (Wrong Repository)
        - POH (Wrong Repository)
        - Gateway
        - Connecting Shop (Wrong Repository)
        - Connecting Prodrisk (Wrong Repository)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which Product version [Other versions should be added in Additional info]
      placeholder: v0.0.0
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Question
      description: What knowledge do you seek?
      placeholder: In a dark place we find ourselves, and a little more knowledge lights our way --Yoda
    validations:
      required: true
